name: PyTest

on:
  push:
    branches:
      - 'hw2'
  pull_request:
    branches:
      - '**'

jobs:
  pytest-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: make test